export const PUBLIC_PAGE_CLASS =
  [
    'bg-slate-950 text-slate-100',
    '[&_.bg-white]:bg-white/5',
    '[&_.bg-gray-50]:bg-transparent',
    '[&_.bg-gray-100]:bg-white/5',
    '[&_.bg-gray-200]:bg-white/10',
    '[&_.bg-slate-50]:bg-transparent',
    '[&_.bg-slate-100]:bg-white/5',
    '[&_.bg-slate-900]:bg-slate-950',
    // tons claros coloridos (evitar “cartões brancos” e highlights claros nas páginas públicas)
    '[&_.bg-orange-50]:bg-white/5',
    '[&_.bg-orange-100]:bg-white/5',
    '[&_.bg-orange-200]:bg-white/10',
    '[&_.bg-yellow-50]:bg-white/5',
    '[&_.bg-yellow-100]:bg-white/5',
    '[&_.bg-amber-50]:bg-white/5',
    '[&_.bg-amber-100]:bg-white/5',
    '[&_.bg-green-50]:bg-white/5',
    '[&_.bg-green-100]:bg-white/5',
    '[&_.bg-emerald-50]:bg-white/5',
    '[&_.bg-emerald-100]:bg-white/5',
    '[&_.bg-blue-50]:bg-white/5',
    '[&_.bg-blue-100]:bg-white/5',
    '[&_.bg-indigo-50]:bg-white/5',
    '[&_.bg-indigo-100]:bg-white/5',
    '[&_.bg-purple-50]:bg-white/5',
    '[&_.bg-purple-100]:bg-white/5',
    '[&_.bg-red-50]:bg-white/5',
    '[&_.bg-red-100]:bg-white/5',
    '[&_.border-gray-100]:border-white/10',
    '[&_.border-gray-200]:border-white/10',
    '[&_.border-gray-300]:border-white/15',
    '[&_.border-gray-800]:border-white/10',
    '[&_.border-slate-200]:border-white/10',
    '[&_.border-slate-300]:border-white/15',
    '[&_.border-blue-100]:border-white/10',
    '[&_.border-blue-200]:border-white/10',
    '[&_.border-green-100]:border-white/10',
    '[&_.border-green-200]:border-white/10',
    '[&_.border-orange-100]:border-white/10',
    '[&_.border-orange-200]:border-white/10',
    '[&_.border-yellow-100]:border-white/10',
    '[&_.border-yellow-200]:border-white/10',
    '[&_.border-red-100]:border-white/10',
    '[&_.border-red-200]:border-white/10',
    '[&_.text-gray-900]:text-white',
    '[&_.text-gray-800]:text-slate-100',
    '[&_.text-gray-700]:text-slate-200',
    '[&_.text-gray-600]:text-slate-300',
    '[&_.text-gray-500]:text-slate-400',
    '[&_.text-gray-400]:text-slate-400',
    '[&_.shadow-sm]:shadow-none',
    '[&_.shadow-md]:shadow-none',
    '[&_.shadow-lg]:shadow-xl',
  ].join(' ');

